windowrule = suppress_event maximize, match:class .*
windowrule = no_focus true, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false
windowrule = border_color rgba(303030ee) rgba(1a1a1aee), match:workspace special:magic

windowrule = float true, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float true, match:class ^(firefox)$, match:title ^(Library)$
windowrule = float true, match:class ^(firefox)$, match:title ^(Page Info)$
windowrule = float true, match:class ^(firefox)$, match:title ^(Developer Tools)$
windowrule = float true, match:class ^(firefox)$, match:title ^(Downloads)$
windowrule = float true, match:class ^(firefox)$, match:title ^(Bitwarden)$


# Brave bitwarden
windowrule = float true, match:class ^(brave).*, match:title ^(_crx_nngceckbapebfimnlniiiahkandclblb)$

# Bitwarden PWA
windowrule = float true, match:class ^(chrome-nngceckbapebfimnlniiiahkandclblb-Default)$

# Brave download
windowrule = float true, match:class ^(xdg-desktop-portal-gtk)$

# Adwaita Bluetooth
windowrule = float true, match:class ^(com.ezratweaver.AdwBluetooth)$

# Wifi
windowrule = float true, match:class ^(iwgtk)$

# Gnome Calculator
windowrule = float true, match:class ^(org.gnome.Calculator)$, match:title ^(Calculator)$
windowrule = float true, match:class ^(org.gnome.Calendar)$, match:title ^(Calendar)$


windowrule = float true, match:title ^(Picture-in-Picture)$
windowrule = pin true, match:title ^(Picture-in-Picture)$
windowrule = size 640 360, match:title ^(Picture-in-Picture)$

windowrule = float true, match:class ^(org.gnome.Loupe)$
windowrule = center true, match:class ^(org.gnome.Loupe)$
windowrule = size 800 800, match:class ^(org.gnome.Loupe)$
