# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a6c4ec92-5a1f-4fcf-a292-63fa57b505d5";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a6c4ec92-5a1f-4fcf-a292-63fa57b505d5".device =
    "/dev/disk/by-uuid/a6c4ec92-5a1f-4fcf-a292-63fa57b505d5";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D439-9905";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Force S3 sleep mode to preserve battery during sleep (idk what that means)
  boot.kernelParams = [ "mem_sleep_default=deep" ];

  # Fix for sdcard reader
  boot.blacklistedKernelModules = [ "firewire_ohci" ];

  # Fix Intel cpu throttling
  services.throttled.enable = true;
}
