# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-ee15cef8-c8b1-41f9-bfce-de3ef6d70623";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ee15cef8-c8b1-41f9-bfce-de3ef6d70623".device =
    "/dev/disk/by-uuid/ee15cef8-c8b1-41f9-bfce-de3ef6d70623";
  boot.initrd.luks.devices."luks-d62ee072-a9ff-4437-9ec7-dc68b14fbff8".device =
    "/dev/disk/by-uuid/d62ee072-a9ff-4437-9ec7-dc68b14fbff8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D1F5-36CA";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-d62ee072-a9ff-4437-9ec7-dc68b14fbff8"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
