# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-4bbfa4d2-8ff2-4649-8b4e-6d2aed0612a8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-4bbfa4d2-8ff2-4649-8b4e-6d2aed0612a8".device =
    "/dev/disk/by-uuid/4bbfa4d2-8ff2-4649-8b4e-6d2aed0612a8";

  # Hibernation / Swap
  boot.initrd.luks.devices."luks-1c5164ec-f62a-42b4-9a43-f40186b25a90".device =
    "/dev/disk/by-uuid/1c5164ec-f62a-42b4-9a43-f40186b25a90";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2A68-F5FD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-1c5164ec-f62a-42b4-9a43-f40186b25a90"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
