# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-b3d68d52-00ec-4054-9f87-09fc3441851f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b3d68d52-00ec-4054-9f87-09fc3441851f".device =
    "/dev/disk/by-uuid/b3d68d52-00ec-4054-9f87-09fc3441851f";

  boot.initrd.luks.devices."luks-09883cd3-af6a-4144-9988-457449e2b496".device =
    "/dev/disk/by-uuid/09883cd3-af6a-4144-9988-457449e2b496";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0031-00E3";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-09883cd3-af6a-4144-9988-457449e2b496"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
